# Site settings
title: The Source
email: info@the-source.it
description: Functional reactive developer in Scala, Kotlin and Typescript. Software architect, tech lead.
baseurl: "/spectral-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://www.the-source.it" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:
about-me: "My name is Joost de Vries. I work as a functional reactive developer in Scala, Kotlin & Typescript. Currently as an independent contracter at Port of Rotterdam. I like to sing, play the saxophone, hike."
chamber-of-commerce: "Kvk 73917737"
# Social settings
500px_url:
facebook_url:
github_url: https://github.com/joost-de-vries
gitlab_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/joostdevries
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jouke

# Build settings
markdown: kramdown
